name: Classroom
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
env:
  ASPNETCORE_ENVIRONMENT: Development
  BUILD_CONFIGURATION: Debug

  APP_PATH: /home/${{ secrets.SSH_USER_NAME }}/lab2

  GATEWAY_PORT: ${{ vars.GATEWAY_PORT }}
  LIBRARY_PORT: ${{ vars.LIBRARY_PORT }}
  RATING_PORT: ${{ vars.RATING_PORT }}
  RESERVATION_PORT: ${{ vars.RESERVATION_PORT }}

jobs:
  Autograding:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: <variant>/postman/collection.json
          environment: <variant>/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true